# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nikita Artyushov
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artyushov.me" # the base hostname & protocol for your site
twitter_username: artyushov
github_username:  artyushov

# Build settings
markdown: kramdown
